const initProps = {
  btnTitle: 'Регистрация',
  btnType: 'submit',
  btnClassName: 'btn btn-primary w-100',
  loginInputType: 'text',
  loginInputName: 'login',
  loginInputId: 'login_input',
  loginTitle: 'Логин',
  passwordInputType: 'password',
  passwordInputName: 'password',
  passwordInputId: 'password_input',
  passwordTitle: 'Пароль',
  passwordError: false,
  passwordErrorMessage: '',
  passwordRepeatTitle: 'Пароль ещё раз',
  passwordRepeatInputId: 'passwordRepeat_input',
  passwordRepeatInputName: 'password_repeat',
  passwordRepeatInputType: 'password',
  passwordRepeatError: false,
  passwordErrorRepeatMessage: '',
  loginLinkText: 'Войти',
  loginLinkUrl: '/login',
  loginLinkClassName: 'link t-center',
  loginError: false,
  loginErrorMessage: '',
  emailInputType: 'email',
  emailInputName: 'email',
  emailInputId: 'email_input',
  emailTitle: 'Почта',
  emailError: false,
  emailErrorMessage: '',
  firstnameTitle: 'Имя',
  firstnameInputId: 'firstname_input',
  firstnameInputName: 'first_name',
  firstnameInputType: 'text',
  firstnameError: false,
  firstnameErrorMessage: '',
  secondnameTitle: 'Фамилия',
  secondnameInputId: 'secondname_input',
  secondnameInputName: 'second_name',
  secondnameInputType: 'text',
  secondnameError: false,
  secondnameErrorMessage: '',
  phoneTitle: 'Телефон',
  phoneInputId: 'phone_input',
  phoneInputName: 'phone',
  phoneInputType: 'phone',
  phoneError: false,
  phoneErrorMessage: '',
}
export { initProps }
